### ISSUE TITLE
Verificação da duração de matérias

### ISSUE THREAD

**Issue by rafamttz** [pstwh/uepgacadonline-flutter#8]
Quando o usuário está na sessão de notas as matérias semestrais possuem notas do "1° Semestre" e "2° Semestre" ao invés de "1° Bimestre" e "2° Bimestre". Precisa ser feito uma verificação para que se a matéria for semestral deve ser mostrado "Bimestre" e caso seja anual mostre "Semestre".

Dessa maneira o usuário não irá ficar confuso!

(nunca duvide do usuário)

**Comment by pstwh** [comment]
Complementando a issue com uma possível solução.

Esse dado pode ser extraído do -1 ou -2 do lado do ano da disciplina.
<img width="145" alt="semestreBimestre" src="https://user-images.githubusercontent.com/11170532/57974709-289c5c00-7993-11e9-816f-11b9fa387cce.png">

Disciplinas sem esse valor são anuais.
